# Generated by Django 5.1.5 on 2025-02-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_activity_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.TextField(),
        ),
    ]
