# Generated by Django 5.1.5 on 2025-02-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_activity_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity',
            new_name='activity_post',
        ),
    ]
