# Generated by Django 5.1.5 on 2025-02-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/static/images/profile/hacker.png', upload_to='profiles/'),
        ),
    ]
