# Generated by Django 5.1.5 on 2025-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_social_name_remove_social_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='official_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
